- hosts: localhost
  become: true
  tasks:
  - name: "Install dependencies"
    apt:
      pkg:
        - shutter
        - peek
        - kolourpaint4
        - gwenview
        - tuxguitar
        - vlc
        - wireshark
        - atom
        - meld
        - dino
        - thunderbird
        - htop
        - keepassx
      state: present
